name: "Publish VTT to staging area"
author: "seravy@gmail.com"

inputs:
  PUBLISHSECRET:
    description: "The secret for publishing."
    required: true

runs:
  using: "docker"
  image: "Dockerfile"
  # args:
  #   - ${{ inputs.PUBLISHSECRET }}
  env: 
    PUBLISHSECRET: ${{ inputs.PUBLISHSECRET }}

branding:
  icon: "mic"
  color: "purple"
