name: "Publish VTT to staging area"
author: "seravy@gmail.com"

runs:
  using: "docker"
  image: "Dockerfile"
  args:
    - ${{ inputs.PUBLISHSECRET }}
  env: 
    PUBLISHSECRET: ${{ secrets.PUBLISHSECRET }}

branding:
  icon: "mic"
  color: "purple"
