name: Publish Staging
on: push
jobs:
  build:
    name: Publish to staging area
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: PublishAction
        id: publishaction
        uses: ./.build/action-staging

        # - shell: bash
        # env:
        #   PUBLISHSECRET: ${{ secrets.PUBLISHSECRET }}
        # run: |
        #   echo secret $PUBLISHSECRET